version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptovalid_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
